# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=1)),
                ('userpassword', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=11)),
                ('mail', models.EmailField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
