# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blogger',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
