# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_article_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=1),
        ),
    ]
