# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_article_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
