# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0008_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comment_admin',
        ),
    ]
